// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for C and C++
// from codepoints https://github.com/FortAwesome/Font-Awesome/raw/6.x/metadata/icons.yml
// for use with font https://github.com/FortAwesome/Font-Awesome/blob/6.x/webfonts/fa-regular-400.ttf, https://github.com/FortAwesome/Font-Awesome/blob/6.x/webfonts/fa-solid-900.ttf

#pragma once

#define FONT_ICON_FILE_NAME_FAR "fa-regular-400.ttf"
#define FONT_ICON_FILE_NAME_FAS "fa-solid-900.ttf"

#define ICON_MIN_FA    0xe005
#define ICON_MAX_16_FA 0xf8ff
#define ICON_MAX_FA    0xf8ff

#define ICON_FA_GEAR      "\xef\x80\x93"  // U+f013
#define ICON_FA_LIGHTBULB "\xef\x83\xab"  // U+f0eb
